version: "3.8"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ".:/app"
    ports:
      - "0.0.0.0:8000:8000"
    environment:
      - stage_app=${stage_app}
    depends_on: 
      - postgres
      - pgadmin4
      - redis-server
  postgres:
    image: "postgres"
    restart: always
    volumes:
      - "./migration_data:/home"
    environment: 
      - TZ=${timezone}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  pgbackups:
    image: "prodrigestivill/postgres-backup-local"
    restart: always
    volumes:
      - "./backups:/backups"
    depends_on:
      - postgres
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_EXTRA_OPTS=-Z9 --schema=public --blobs
      - SCHEDULE=@every 2h00m00s
      - BACKUP_KEEP_DAYS=7
      - BACKUP_KEEP_WEEKS=4
      - BACKUP_KEEP_MONTHS=6
      - HEALTHCHECK_PORT=80
  pgadmin4:
    image: "dpage/pgadmin4"
    ports: 
      - "0.0.0.0:5437:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
  redis-server:
    image: "redis"
    sysctls:
      - net.core.somaxconn=511

networks:
  default:
    name: restapi_networks
