name: Tests & Deploy
on: [push, pull_request]
defaults:
  run:
    working-directory: ./restapi
jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Copy .env file
        run: cp .env.example .env
      - name: Build the stack
        run: docker-compose up -d
      - name: Migrate Database
        run: bash scripts/migrate.sh
      - name: Test
        run: bash scripts/test.sh
      - uses: actions/setup-python@master
        with:
          python-version: '3.8'
      - name: Install Coveralls
        run: pip install coveralls
      - name: Coveralls
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          coveralls --service=github

  deploy:
    needs: test
    runs-on: ubuntu-18.04
    steps:
      - name: deploy on vps
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          command_timeout: 20m
          script: bash deploy_backend.sh
